server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-consumer
          uri: lb://service-consumer
          predicates:
            - Path: /consumer/**
              filters:
                - StripPrefix: 1
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: gateway




